test_robot_control_bridge_node:
  ros__parameters:
    controller_namespace: "aic_controller"
    test_mode: "joint"
    test_joint_targets: >
      [
        -1.57, -1.57, -1.57, -1.57, 1.57, -1.57
      ]
    log_filepath: ""
    target_pose_stiffness: [1000.0, 150.0]
    target_pose_damping: [200.0, 54.7723]
    target_joint_stiffness: [25.0, 25.0, 25.0, 5.0, 5.0, 5.0]
    target_joint_damping: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
    publish_duration: 3.0
    stop_duration: 2.0
