name: aic
channels:
  - robostack-kilted
  - conda-forge
dependencies:
  - colcon-common-extensions
  - gxx=13
  - pip
  - pip:
    - lerobot==0.4.2
    - git+https://github.com/koonpeng/lerobot-ros@831bdbcd77e2af5568f8508396b5defc48862b84#subdirectory=lerobot_robot_ros
    - git+https://github.com/koonpeng/lerobot-ros@831bdbcd77e2af5568f8508396b5defc48862b84#subdirectory=lerobot_teleoperator_devices
  - rosdep
  - ros-kilted-control-msgs
  - ros-kilted-geometry-msgs
  - ros-kilted-moveit-msgs
  - ros-kilted-rclpy
  - ros-kilted-rmw-zenoh-cpp
  - ros-kilted-ros-core
  - ros-kilted-sensor-msgs
  - ros-kilted-std-msgs
  - vcstool
