/*
 * Copyright (C) 2025 Intrinsic Innovation LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AIC_CONTROLLER__AIC_CONTROLLER_HPP_
#define AIC_CONTROLLER__AIC_CONTROLLER_HPP_

#include <memory>
#include <optional>
#include <string>

#include "aic_controller/actions/cartesian_impedance_action.hpp"
#include "controller_interface/controller_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"

// Interfaces
#include "aic_control_interfaces/msg/joint_motion_update.hpp"
#include "aic_control_interfaces/msg/motion_update.hpp"
#include "aic_control_interfaces/msg/trajectory_generation_mode.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"

// Auto-generated by generate_parameter_library
#include "aic_controller/aic_controller_parameters.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "semantic_components/force_torque_sensor.hpp"


//==============================================================================
namespace aic_controller {

using JointMotionUpdate = aic_control_interfaces::msg::JointMotionUpdate;
using MotionUpdate = aic_control_interfaces::msg::MotionUpdate;
using TrajectoryGenerationMode =
    aic_control_interfaces::msg::TrajectoryGenerationMode;
using JointTrajectoryPoint = trajectory_msgs::msg::JointTrajectoryPoint;

//==============================================================================
enum class ControlMode : uint8_t {
    Invalid = 0,
    Admittance = 1,
    Impedance = 2
};

//==============================================================================
enum class InterpolationMode : uint8_t {
  Invalid = 0,
  Linear = 1,
};

//==============================================================================
enum class TargetType : uint8_t {
  Invalid = 0,
  Joint = 1,
  Cartesian = 2,
};

//==============================================================================
/**
 * The AIC Controller subscribes to user commands at a lower frequency and
 * based on the control mode:
 * 1. Admittance mode: Outputs interpolated user commands at
 * a higher frequency to the admittance controller.
 * 2. Impedance mode: Outputs control commands to the robot arm's hardware
 * interface from an internal impedance controller implementation.
 */
class Controller : public controller_interface::ControllerInterface {
 public:
  Controller();

  /**
   * @copydoc controller_interface::ControllerInterface::command_interface_configuration()
   */
  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  /**
   * @copydoc controller_interface::ControllerInterface::state_interface_configuration()
   */
  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_init()
   */
  controller_interface::CallbackReturn on_init() override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_configure()
   */
  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_activate()
   */
  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::on_deactivate()
   */
  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  /**
   * @copydoc controller_interface::ControllerInterface::update()
   */
  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 private:
  /**
   * @brief Update controller parameters and compute commands based on control
   * law
   *
    * @param control_mode Control mode to use for updating and writing commands
   * @param target_type Target type to use for updating and writing commands
   * @return controller_interface::return_type
   */
  controller_interface::return_type update_and_write_commands(
      const ControlMode& control_mode, const TargetType& target_type);

  /**
   * @brief Reads state values from hardware interfaces and reference values
   * from ROS subscribers
   */
	[[nodiscard]]
  bool sense();

  /**
   * @brief Update cartesian reference by limiting the target states to stay
   * within limits and then interpolating their values.
   *
   * @return true Update successful
   * @return false Update failed
   */
	[[nodiscard]]
  bool update_joint_reference();

  /**
   * @brief Update cartesian reference by limiting the target states to stay
   * within limits and then interpolating their values.
   *
   * @return true Update successful
   * @return false Update failed
   */
	[[nodiscard]]
  bool update_cartesian_reference();

  /**
   * @brief Applies linear interpolation to the reference values to minimize
   * discontinuities from the current reference to the target reference.
   *
   * @param reference_state
   * @param target_state
   * @param new_reference
   * @return true
   * @return false
   */
	[[nodiscard]]
  bool update_next_command_linear_interpolation(
      const JointTrajectoryPoint& reference_state,
      const JointTrajectoryPoint& target_state,
      JointTrajectoryPoint& new_reference);

  /**
   * @brief Update fields of state_current with joint states from hardware
   * interfaces
   *
   * @param state_current Sensed joint states
   */
  void read_state_from_hardware(JointTrajectoryPoint& state_current);

  /**
   * @brief Write values from state_command to claimed command interfaces
   *
   * @param state_command Commanded joint states
   */
  void write_state_to_hardware(const JointTrajectoryPoint& state_command);

  // controller parameters
  std::shared_ptr<aic_controller::ParamListener> param_listener_;
  aic_controller::Params params_;

  std::size_t num_joints_;
  std::vector<std::string> command_joint_names_;

  TargetType target_type_;
  ControlMode control_mode_;
  InterpolationMode interpolation_mode_;

  bool has_position_state_interface_;
	bool has_velocity_state_interface_;
	bool has_acceleration_state_interface_;

  static constexpr std::array<std::string_view, 3> allowed_state_interface_types_{
      hardware_interface::HW_IF_POSITION,
			hardware_interface::HW_IF_VELOCITY,
      hardware_interface::HW_IF_ACCELERATION
	};

  // Impedance controller for cartesian targets
  std::unique_ptr<CartesianImpedanceAction> cartesian_impedance_action_;

	// ROS2 subscribers for user commands
  rclcpp::Subscription<MotionUpdate>::SharedPtr motion_update_sub_;
  rclcpp::Subscription<JointMotionUpdate>::SharedPtr joint_motion_update_sub_;

  // Real-time boxes for thread-safe access
  realtime_tools::RealtimeThreadSafeBox<MotionUpdate> motion_update_rt_;
  realtime_tools::RealtimeThreadSafeBox<JointMotionUpdate>
      joint_motion_update_rt_;
  JointMotionUpdate joint_motion_update_;
  MotionUpdate motion_update_;

  // Last value written to controller interfaces
  JointTrajectoryPoint last_commanded_state_;
  // Set points for next control update computer after interpolations
  std::optional<JointTrajectoryPoint> next_command_;
  // Desired target state read from JointMotionUpdate user commands
  std::optional<JointTrajectoryPoint> target_state_;

  double time_to_target_seconds_;

  // Latest joint states read from hardware interface
  JointTrajectoryPoint current_state_;
};

}  // namespace aic_controller

#endif  // AIC_CONTROLLER__AIC_CONTROLLER_HPP_
