/*
 * Copyright (C) 2025 Intrinsic Innovation LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AIC_CONTROLLER__AIC_CONTROLLER_HPP_
#define AIC_CONTROLLER__AIC_CONTROLLER_HPP_

#include "aic_control_interfaces/msg/joint_motion_update.hpp"
#include "aic_control_interfaces/msg/motion_update.hpp"
#include "aic_control_interfaces/msg/trajectory_generation_mode.hpp"
#include "aic_controller/cartesian_impedance_controller.hpp"
#include "controller_interface/controller_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
// auto-generated by generate_parameter_library
#include "aic_controller/aic_controller_parameters.hpp"
#include "aic_controller/joint_state.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "semantic_components/force_torque_sensor.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"

/**
 * AICController subscribes to user commands at a lower frequency and
 * based on the control mode:
 * 1. Admittance mode: Outputs interpolated user commands at
 * a higher frequency to the admittance controller.
 * 2. Impedance mode: Outputs control commands to the robot arm's hardware
 * interface from an internal impedance controller implementation.
 */
namespace aic_controller {
using aic_control_interfaces::msg::JointMotionUpdate;
using aic_control_interfaces::msg::MotionUpdate;
using aic_control_interfaces::msg::TrajectoryGenerationMode;
using trajectory_msgs::msg::JointTrajectoryPoint;

enum ControlMode {
  UNSPECIFIED_CONTROL_MODE,
  ADMITTANCE,
  IMPEDANCE,
};

enum InterpolationMode {
  LINEAR,
  REFLEXXES,
  MINIMAL_SPLINES,
};

enum TargetType {
  JOINT,
  CARTESIAN,
};

Eigen::Map<Eigen::VectorXd> ToEigen(std::vector<double> array, int ndof) {
  return Eigen::Map<Eigen::VectorXd>(array.data(), ndof);
}

class AICController : public controller_interface::ControllerInterface {
 public:
  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  // Add joint and ft sensor states
  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 protected:
  controller_interface::return_type update_and_write_commands_cartesian();

  controller_interface::return_type update_and_write_commands_joints();

  /**
   * @brief Update reference values by limiting the target states to stay
   * within limits and then interpolating their values.
   */
  bool update_reference_joints();

  /**
   * @brief Update reference values by limiting the target states to stay
   * within limits and then interpolating their values.
   */
  bool update_reference_cartesian();

  /**
   * @brief Performs
   *
   * @param target_state
   * @return JointTrajectoryPoint
   */
  JointTrajectoryPoint update_reference_joints_linear_interpolation(
      const JointTrajectoryPoint& target_state_msg);

  /**
   * @brief Reads state values from hardware interfaces and reference values
   * from subscribers
   */
  controller_interface::return_type sense();

  /**
   * @brief Read joint state values from hardware interfaces
   *
   * @param state_current
   */
  void read_joint_states(JointTrajectoryPoint& state_current);

  /**
   * @brief Write joint positions to command interface
   *
   * @param state_command
   */
  void write_reference_joint_position(
      const JointTrajectoryPoint& state_command);

  // controller parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  size_t num_joints_{0};
  std::vector<std::string> command_joint_names_;
  double frequency_hz_{0};

  TargetType target_type_{TargetType::JOINT};
  ControlMode control_mode_{ControlMode::UNSPECIFIED_CONTROL_MODE};
  InterpolationMode interpolation_mode_{InterpolationMode::LINEAR};

  bool has_position_state_interface_ = false;
  bool has_velocity_state_interface_ = false;
  bool has_acceleration_state_interface_ = false;
  bool has_position_command_interface_ = false;
  bool has_effort_command_interface_ = false;

  const std::vector<std::string> allowed_state_interface_types_ = {
      hardware_interface::HW_IF_POSITION, hardware_interface::HW_IF_VELOCITY,
      hardware_interface::HW_IF_ACCELERATION};

  // Impedance controller for cartesian targets
  std::unique_ptr<CartesianImpedanceController> cartesian_impedance_controller_;

  rclcpp::Subscription<MotionUpdate>::SharedPtr motion_update_sub_;
  rclcpp::Subscription<JointMotionUpdate>::SharedPtr joint_motion_update_sub_;
  // todo(johntgz) add impedance controller state message and publisher

  // real-time boxes for thread-safe access
  realtime_tools::RealtimeThreadSafeBox<MotionUpdate> motion_update_rt_;
  realtime_tools::RealtimeThreadSafeBox<JointMotionUpdate>
      joint_motion_update_rt_;
  JointMotionUpdate joint_motion_update_;
  MotionUpdate motion_update_;

  // Last value written to controller interfaces
  JointTrajectoryPoint last_commanded_joints_;
  // interpolated reference joint values
  std::optional<JointTrajectoryPoint> reference_joints_;
  // State commanded by JointMotionUpdate user commands
  std::optional<JointTrajectoryPoint> target_joint_msg_;
  JointState target_joint_;

  double time_to_target_seconds_{0.0};
  double remaining_time_to_target_seconds_{0.0};

  // Latest joint states read from hardware interface
  JointTrajectoryPoint joint_state_;
};

}  // namespace aic_controller

#endif  // AIC_CONTROLLER__AIC_CONTROLLER_HPP_
