/*
 * Copyright (C) 2025 Intrinsic Innovation LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AIC_CONTROLLER__AIC_CONTROLLER_HPP_
#define AIC_CONTROLLER__AIC_CONTROLLER_HPP_

#include <memory>
#include <optional>
#include <string>

#include "aic_control_interfaces/msg/joint_motion_update.hpp"
#include "aic_control_interfaces/msg/motion_update.hpp"
#include "aic_control_interfaces/msg/trajectory_generation_mode.hpp"
#include "aic_controller/cartesian_impedance_controller.hpp"
#include "controller_interface/controller_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
// auto-generated by generate_parameter_library
#include "aic_controller/aic_controller_parameters.hpp"
#include "aic_controller/joint_limits.hpp"
#include "aic_controller/joint_state.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "semantic_components/force_torque_sensor.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"

/**
 * The AIC Controller subscribes to user commands at a lower frequency and
 * based on the control mode:
 * 1. Admittance mode: Outputs interpolated user commands at
 * a higher frequency to the admittance controller.
 * 2. Impedance mode: Outputs control commands to the robot arm's hardware
 * interface from an internal impedance controller implementation.
 */
namespace aic {
using JointMotionUpdate = aic_control_interfaces::msg::JointMotionUpdate;
using MotionUpdate = aic_control_interfaces::msg::MotionUpdate;
using TrajectoryGenerationMode =
    aic_control_interfaces::msg::TrajectoryGenerationMode;
using JointTrajectoryPoint = trajectory_msgs::msg::JointTrajectoryPoint;

enum class ControlMode : uint8_t { Invalid = 0, Admittance = 1, Impedance = 2 };

enum class InterpolationMode : uint8_t {
  Invalid = 0,
  Linear = 1,
  Reflexxes = 2,
  MinimalSplines = 3
};

enum class TargetType : uint8_t {
  Invalid = 0,
  Joint = 1,
  Cartesian = 2,
};

Eigen::Map<Eigen::VectorXd> ToEigen(std::vector<double> array, int num_joints) {
  return Eigen::Map<Eigen::VectorXd>(array.data(), num_joints);
}

class Controller : public controller_interface::ControllerInterface {
 public:
  Controller();

  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 private:
  /**
   * @brief Update controller parameters and compute commands based on control
   * law
   *
   * @param target_type
   * @return controller_interface::return_type
   */
  controller_interface::return_type update_and_write_commands(
      const ControlMode& control_mode, const TargetType& target_type);

  /**
   * @brief Reads state values from hardware interfaces and reference values
   * from ROS subscribers
   */
  bool sense();

  /**
   * @brief Update cartesian reference by limiting the target states to stay
   * within limits and then interpolating their values.
   *
   * @return true Update successful
   * @return false Update failed
   */
  bool update_joint_reference();

  /**
   * @brief Update cartesian reference by limiting the target states to stay
   * within limits and then interpolating their values.
   *
   * @return true Update successful
   * @return false Update failed
   */
  bool update_cartesian_reference();

  /**
   * @brief Applies linear interpolation to the reference values to minimize
   * discontinuities from the current reference to the target reference.
   *
   * @param reference_state
   * @param target_state
   * @param new_reference
   * @return true
   * @return false
   */
  bool update_reference_joints_linear_interpolation(
      const JointState& reference_state, const JointState& target_state,
      JointState& new_reference);

  /**
   * @brief Update fields of state_current with joint states from hardware
   * interfaces
   *
   * @param state_current Sensed joint states
   */
  void read_state_from_hardware(JointState& state_current);

  /**
   * @brief Write values from state_command to claimed command interfaces
   *
   * @param state_command Commanded joint states
   */
  void write_state_to_hardware(const JointTrajectoryPoint& state_command);

  // controller parameters
  std::shared_ptr<aic_controller::ParamListener> param_listener_;
  aic_controller::Params params_;

  std::size_t num_joints_{0};
  std::vector<std::string> command_joint_names_;
  double frequency_hz_{0};
  JointLimits joint_limits_;

  TargetType target_type_{TargetType::Invalid};
  ControlMode control_mode_{ControlMode::Invalid};
  InterpolationMode interpolation_mode_{InterpolationMode::Invalid};

  bool has_position_state_interface_, has_velocity_state_interface_,
      has_acceleration_state_interface_;

  const std::vector<std::string> allowed_state_interface_types_ = {
      hardware_interface::HW_IF_POSITION, hardware_interface::HW_IF_VELOCITY,
      hardware_interface::HW_IF_ACCELERATION};

  // Impedance controller for cartesian targets
  std::unique_ptr<CartesianImpedanceController> cartesian_impedance_controller_;

  rclcpp::Subscription<MotionUpdate>::SharedPtr motion_update_sub_;
  rclcpp::Subscription<JointMotionUpdate>::SharedPtr joint_motion_update_sub_;

  // real-time boxes for thread-safe access
  realtime_tools::RealtimeThreadSafeBox<MotionUpdate> motion_update_rt_;
  realtime_tools::RealtimeThreadSafeBox<JointMotionUpdate>
      joint_motion_update_rt_;
  JointMotionUpdate joint_motion_update_;
  MotionUpdate motion_update_;

  // Last value written to controller interfaces
  JointState last_commanded_joints_;
  // Variable used in interpolation of target
  std::optional<JointState> reference_joints_;
  // State commanded by JointMotionUpdate user commands
  std::optional<JointState> target_joints_;

  double time_to_target_seconds_;
  double remaining_time_to_target_seconds_;

  // Latest joint states read from hardware interface
  JointState joint_state_;
};

}  // namespace aic

#endif  // AIC_CONTROLLER__AIC_CONTROLLER_HPP_
