/*
 * Copyright (C) 2025 Intrinsic Innovation LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AIC_CONTROLLER__AIC_CONTROLLER_HPP_
#define AIC_CONTROLLER__AIC_CONTROLLER_HPP_

// #include "aic_controller/impedance_rule.hpp"
#include "aic_control_interfaces/msg/joint_motion_update.hpp"
#include "aic_control_interfaces/msg/motion_update.hpp"
#include "aic_control_interfaces/msg/trajectory_generation_mode.hpp"
#include "controller_interface/controller_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"
// auto-generated by generate_parameter_library
#include "aic_controller/aic_controller_parameters.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "semantic_components/force_torque_sensor.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"

/**
 * AICController is a controller that subscribes to user commands at a lower
 * frequency and depending on the control mode, forwards the interpolated
 * commands at a higher frequency to the admittance controller or outputs a
 * command from an impedance controller implementation
 */
namespace aic_controller {
using aic_control_interfaces::msg::JointMotionUpdate;
using aic_control_interfaces::msg::MotionUpdate;
using aic_control_interfaces::msg::TrajectoryGenerationMode;
using trajectory_msgs::msg::JointTrajectoryPoint;

enum ControlMode {
  UNSPECIFIED_CONTROL_MODE,
  ADMITTANCE,
  IMPEDANCE,
};

enum InterpolationMode {
  UNSPECIFIED_INTERPOLATION_MODE,
  LINEAR,
  REFLEXXES,
  MINIMAL_SPLINES,
};

enum TargetType {
  JOINT,
  CARTESIAN,
};

class AICController : public controller_interface::ControllerInterface {
 public:
  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  // Add joint and ft sensor states
  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::return_type update(
      const rclcpp::Time& time, const rclcpp::Duration& period) override;

 protected:
  controller_interface::return_type update_and_write_commands_cartesian();

  controller_interface::return_type update_and_write_commands_joints();

  /// Update reference values by limiting them and then performing interpolation
  bool update_reference_joints();

  /// Update reference values by limiting them and then performing interpolation
  bool update_reference_cartesian();

  JointTrajectoryPoint update_reference_joints_linear_interpolation(
      const JointTrajectoryPoint& msg);

  /// Update reference from input topics when not in chained mode. This method
  /// is called before 'update'
  controller_interface::return_type sense();

  /**
   * @brief Read force torque sensor values from hardware interfaces and set
   * force torque sensor readings
   */
  void read_force_torque_sensor_states(geometry_msgs::msg::Wrench& ft_values);

  /**
   * @brief Read joint state values from hardware interfaces and set current
   * joint states
   */
  void read_joint_states(JointTrajectoryPoint& state_current);

  /**
   * @brief Write values from state_command to admittance controller
   */
  void write_reference_to_admittance_controller(
      const JointTrajectoryPoint& state_command);

  // controller parameters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  size_t num_joints_ = 0;
  std::vector<std::string> command_joint_names_;

  bool has_position_state_interface_ = false;  // used by impedance controller
  bool has_velocity_state_interface_ = false;  // used by impedance controller
  bool has_acceleration_state_interface_ = false;  // unused
  bool has_position_command_interface_ =
      false;  // used by admittance controller
  bool has_velocity_command_interface_ =
      false;  // used by admittance controller
  bool has_acceleration_command_interface_ = false;  // unused
  bool has_effort_command_interface_ = false;  // used by impedance controller

  const std::vector<std::string> allowed_state_interface_types_ = {
      hardware_interface::HW_IF_POSITION, hardware_interface::HW_IF_VELOCITY,
      hardware_interface::HW_IF_ACCELERATION};

  // Impedance rule and dependent variables;
  //   std::unique_ptr<aic_controller::ImpedanceRule> impedance_;

  // force torque sensor
  std::unique_ptr<semantic_components::ForceTorqueSensor> force_torque_sensor_;

  rclcpp::Subscription<MotionUpdate>::SharedPtr motion_update_sub_;
  rclcpp::Subscription<JointMotionUpdate>::SharedPtr joint_motion_update_sub_;
  // todo(@johntgz) add impedance controller state message and publisher

  // real-time boxes
  realtime_tools::RealtimeThreadSafeBox<MotionUpdate> motion_update_command_;
  realtime_tools::RealtimeThreadSafeBox<JointMotionUpdate>
      joint_motion_update_command_;
  JointMotionUpdate joint_motion_update_msg_;
  MotionUpdate motion_update_msg_;

  TargetType target_type_{TargetType::JOINT};
  ControlMode control_mode_{ControlMode::UNSPECIFIED_CONTROL_MODE};
  InterpolationMode interpolation_mode_{
      InterpolationMode::UNSPECIFIED_INTERPOLATION_MODE};

  // last written command written to controller
  JointTrajectoryPoint last_commanded_joints_;
  // reference_joints_: interpolated joint reference values passed to admittance
  // controller
  std::optional<JointTrajectoryPoint> reference_joints_;
  // target_joint_state_: state commanded by JointMotionUpdate user commands
  std::optional<JointTrajectoryPoint> target_joint_state_;

  double time_to_target_seconds_{0.0};

  // joint_state_: Current state of joints
  JointTrajectoryPoint joint_state_;
  // ft_values_: values read from the force torque sensor
  geometry_msgs::msg::Wrench ft_values_;
};

}  // namespace aic_controller

#endif  // AIC_CONTROLLER__AIC_CONTROLLER_HPP_
