/*
 * Copyright (C) 2025 Intrinsic Innovation LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AIC_CONTROLLER__CARTESIAN_IMPEDANCE_CONTROLLER_HPP_
#define AIC_CONTROLLER__CARTESIAN_IMPEDANCE_CONTROLLER_HPP_

#include <Eigen/Core>

// auto-generated by generate_parameter_library
#include "aic_controller/aic_controller_parameters.hpp"
#include "aic_controller/cart_state.hpp"
#include "aic_controller/joint_limits.hpp"
#include "aic_controller/joint_state.hpp"
#include "controller_interface/controller_interface_base.hpp"
#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "kinematics_interface/kinematics_interface.hpp"
#include "pluginlib/class_loader.hpp"

namespace aic {
using trajectory_msgs::msg::JointTrajectoryPoint;

struct CartesianImpedanceParameters {};

class CartesianImpedanceController {
 public:
  CartesianImpedanceController(unsigned int ndof,
                               aic_controller::Params params);

  static std::unique_ptr<CartesianImpedanceController> Create(
      const std::shared_ptr<aic_controller::ParamListener>& param_listener);

  /**
   * @brief Loads the inverse kinematic plugin given the robot description
   *
   * @param node lifecycle node
   * @param robot_description robot description used by kinematics plugin
   * @return controller_interface::return_type
   */
  controller_interface::return_type Configure(
      const std::shared_ptr<rclcpp_lifecycle::LifecycleNode>& node);

  /**
   * @brief Generates a target torque vector with the control torque given the
   * nullspace, tool goal, sensed joint position and velocity, and control
   * parameters.
   *
   * @param tool_target Target state of tool control frame
   * @param impedance_params Impedance controller parameters
   * @param joint_limits Joint limits on joint position, velocity, accelration
   * and further derivatives
   * @return Eigen::Matrix<double, 6, 1>
   */
  Eigen::Matrix<double, 6, 1> Compute(
      const CartState& tool_target,
      const CartesianImpedanceParameters& impedance_params,
      const JointLimits& joint_limits);

  /**
   * @brief Estimates the end-effector cartesian pose estimate given the joint
   * positions
   */
  bool Update(const JointState& current_sensed);

 private:
  // Number of robot joints
  const std::size_t ndof_;

  // controller parameters
  aic_controller::Params params_;
};

}  // namespace aic

#endif  // AIC_CONTROLLER__CARTESIAN_IMPEDANCE_CONTROLLER_HPP_
