id {
  package: "ai.intrinsic"
  name: "write_to_kv_store"
}
display_name: "Write To KV Store"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Skill that writes generic Protobuf payloads to the Key-Value store at a specified storage location."
}
options {
  supports_cancellation: false
  cc_config {
    create_skill: "::WriteToKVStore::CreateSkill"
  }
}
parameter {
  message_full_name: "ai.flowstate.WriteToKVStoreParams"
  default_value: {
    type_url: "type.googleapis.com/ai.flowstate.WriteToKVStoreParams"
  }
}
return_type {
  message_full_name: "ai.flowstate.WriteToKVStoreResult"
}
