# proto-file: https://github.com/intrinsic-ai/sdk/blob/main/intrinsic/skills/proto/skill_manifest.proto
# proto-message: intrinsic_proto.skill.SkillManifest
id {
  package: "ai.intrinsic"
  name: "start_recording_skill"
}
display_name: "Start Recording Skill"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Skill that starts ROS 2 bag recording via aic_logger."
}
options {
  supports_cancellation: false
  cc_config {
    create_skill: "::StartRecordingSkill::CreateSkill"
  }
}
dependencies {
}
parameter {
  message_full_name: "ai.flowstate.StartRecordingSkillParams"
  default_value: {
    type_url: "type.googleapis.com/ai.flowstate.StartRecordingSkillParams"
  }
}
return_type {
  message_full_name: "ai.flowstate.StartRecordingSkillResult"
}
