metadata {
  id {
    package: "ai.intrinsic"
    name: "aic_model"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "Participant Policy Node."
  }
  display_name: "Participant Policy Node"
}
service_def {
  config_message_full_name: "aic.AICModelConfig"
  real_spec {
    image {
      archive_filename: "aic_model.tar"
      settings {
        resource_requirements {
          limits {
            key: "nvidia.com/gpu"
            value: "1"
          }
        }
      }
    }
  }
  sim_spec {
    image {
      archive_filename: "aic_model.tar"
      settings {
        resource_requirements {
          limits {
            key: "nvidia.com/gpu"
            value: "1"
          }
        }
      }
    }
  } 
}
assets {
  default_configuration_filename: "default_config.binarypb"
  parameter_descriptor_filename: "parameter-descriptor-set.proto.bin"
  image_filenames: ["aic_model.tar"]
}
