ARG CONTAINER_IMAGE=my-solution:v1


FROM ubuntu:24.04 AS sdk-builder
RUN apt-get update && apt-get install -y \
    curl git patch build-essential python3 libxml2-dev liblttng-ust-dev \
    && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=0.67.2 bash
ENV PATH="/root/.pixi/bin:${PATH}"
WORKDIR /workspace
# Copy manifests & local dependencies for pixi environment
COPY aic/pixi.toml aic/pixi.lock aic/robostack_mapping.json ./
COPY aic/aic_interfaces/ ./aic_interfaces/
COPY aic/aic_example_policies/ ./aic_example_policies/
COPY aic/aic_model/ ./aic_model/
COPY aic/aic_utils/ ./aic_utils/
RUN pixi install --frozen --environment skill-build
# Build intrinsic_sdk_cmake so Python protos (intrinsic.resources.proto) are generated
COPY sdk-ros/ ./sdk-ros/
RUN pixi run --frozen --environment skill-build colcon build \
    --merge-install \
    --cmake-args -DCMAKE_BUILD_TYPE=Release \
    --event-handlers=console_direct+ \
    --packages-up-to intrinsic_sdk_cmake \
    --base-paths sdk-ros
# Compile aic_model_config.proto to Python directly into the install site-packages
COPY aic/flowstate/services/aic_model/aic_model_config.proto ./
RUN pixi run --frozen protoc \
    --python_out=/workspace/install/lib/python3.12/site-packages \
    aic_model_config.proto


FROM ${CONTAINER_IMAGE} AS base

# Copy all built Intrinsic SDK Python packages & aic_model_config_pb2 into /opt/intrinsic_sdk
COPY --from=sdk-builder /workspace/install/lib/python3.12/site-packages /opt/intrinsic_sdk/site-packages
# Add /opt/intrinsic_sdk/site-packages to PYTHONPATH so any Python execution finds the SDK
ENV PYTHONPATH="/opt/intrinsic_sdk/site-packages:${PYTHONPATH}"

# Set ROS 2 Kilted RMW implementation to Zenoh
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp

# Skip router check attempts and set router address
ENV ZENOH_ROUTER_CHECK_ATTEMPTS=-1
ENV AIC_ROUTER_ADDR='zenoh-router.app-intrinsic-base.svc.cluster.local:7447'

# Enable GPU support
ENV LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/bin:${LD_LIBRARY_PATH:-}"