---
# Tier2 scoring configuration.

# List of entity pairs to monitor.
plugs:
  - plug:
      name: "sfp_sc_cable::sfp_module_link"
      type: "sfp"
  - plug:
      name: "sfp_sc_cable::sc_plug_link"
      type: "sc"

ports:
  - port:
      name: "sfp_module"
      type: "sfp"
  - port:
      name: "sfp_module"
      type: "sfp"
  - port:
      name: "other_sfp_module"
      type: "sfp"
