syntax = "proto3";

package ai.flowstate;

message LifecycleTransitionSkillParams {
  string node_name = 1;
  Transition transition = 2;

  // Enum values must match the ROS 2 lifecycle transition definitions in
  // https://docs.ros.org/en/kilted/p/lifecycle_msgs/msg/Transition.html
  enum Transition {
    create = 0;
    configure = 1;
    cleanup = 2;
    activate = 3;
    deactivate = 4;
    unconfigured_shutdown = 5;
    inactive_shutdown = 6;
    active_shutdown = 7;
    destroy = 8;
  }

  double timeout = 3;
}

message LifecycleTransitionSkillResult {
  bool success = 1;
  string message = 2;
}
