# Service to start the engine

string[2] plug_name
string[2] port_name
string[2] target_module_name

uint64 time_limit

bool reset # Whether to reset the engine
---
bool success             # indicate successful reset
string message
