# Service to stop the recording for a trial and optionally return the result

bool finished # Whether the full task is finished and it should be scored
---
bool success             # indicate successful reset
string message
