FROM docker.io/library/ros:kilted-ros-base AS build

# Add base dependencies
COPY aic/aic_interfaces/aic_control_interfaces /ws_aic/src/aic/aic_control_interfaces
COPY aic/aic_interfaces/aic_engine_interfaces /ws_aic/src/aic/aic_engine_interfaces
COPY aic/aic_interfaces/aic_task_interfaces /ws_aic/src/aic/aic_task_interfaces
COPY aic/aic_scoring /ws_aic/src/aic/aic_scoring
COPY aic/aic_engine /ws_aic/src/aic/aic_engine
COPY sdk-ros /ws_aic/src/sdk-ros

# Install dependencies
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt update && apt upgrade -y && \
  # undeclared deps
  apt install python3-numpy && \
  apt install ros-kilted-rmw-zenoh-cpp -y && \
  cd /ws_aic && \
  rosdep install --from-path src --ignore-src --rosdistro kilted -yr

# Build the workspace
SHELL ["/bin/bash", "-c"]
RUN --mount=type=cache,target=/ws_aic/build,sharing=locked \
  cd /ws_aic \
  && . /opt/ros/kilted/setup.bash \
  && colcon build --packages-up-to aic_engine --cmake-args -DCMAKE_BUILD_TYPE=Release --merge-install --executor sequential \
  && rm -rf /ws_aic/log /ws_aic/src

COPY --chmod=755 <<"EOF" /entrypoint.sh
#!/bin/bash
set -e

. /ws_aic/install/setup.bash
export RMW_IMPLEMENTATION=rmw_zenoh_cpp
export ZENOH_ROUTER_CHECK_ATTEMPTS=-1
export AIC_ROUTER_ADDR='zenoh-router.app-intrinsic-base.svc.cluster.local:7447'
ZENOH_CONFIG_OVERRIDE='connect/endpoints=["tcp/'"$AIC_ROUTER_ADDR"'"]'
ZENOH_CONFIG_OVERRIDE+=';transport/shared_memory/enabled=false'
export ZENOH_CONFIG_OVERRIDE

exec ros2 run aic_engine aic_engine --ros-args -p use_sim_time:=true
EOF

ENTRYPOINT ["/entrypoint.sh"]
